# Generated by Django 5.1.4 on 2025-01-05 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="login",
            new_name="user",
        ),
    ]
